# Generated by Django 5.1.4 on 2025-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planetarium",
            "0002_alter_ticket_options_alter_astronomyshow_show_theme_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "show_session"),
                name="unique_row_seat_show_session",
            ),
        ),
    ]
